spring.application.name=backend
# ===========================
# PostgreSQL NeonCloud
# ===========================
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true


# Keycloak
keycloak.auth-server-url=http://localhost:8080
keycloak.realm=myrealm
keycloak.client-id=myclient
# Si ton client Keycloak est "confidential", ajoute son secret ici.
keycloak.client-secret=

spring.security.oauth2.resourceserver.jwt.issuer-uri=${keycloak.auth-server-url}/realms/${keycloak.realm}


server.port=8081
