spring.application.name=backend
# ===========================
# PostgreSQL NeonCloud
# ===========================
spring.datasource.url=jdbc:postgresql://ep-fancy-thunder-alprf8kd-pooler.c-3.eu-central-1.aws.neon.tech/gestionconge?user=neondb_owner&password=npg_pAqm3Dkf2FKH&sslmode=require&channelBinding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_pAqm3Dkf2FKH
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

server.port=8081

# JWT
# Clé secrète JWT (>=32 caractères) — ajustez pour la prod ou utilisez une variable d'environnement
app.jwt.secret=0123456789ABCDEF0123456789ABCDEF
app.jwt.expiration-ms=86400000
app.jwt.cookie-name=access_token
app.jwt.cookie-secure=false
